name: "OpenHAB"
description: "OpenHAB empowering the smart home"
version: "4.0.4"
slug: "openhab"
init: false
usb: true
uart: true
udev: true
arch:
  - amd64
map:
  - addon_config:rw
  - backup:rw
host_network: true
